cloud:
  aws:
    credentials:
      access-key: AKIASJZJOCOX5PNZQ7OC
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: carrentalsytem


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 15MB
      max-request-size: 30MB
server:
  port: 8080
