cloud:
  aws:
    credentials:
      access-key: AKIAZEO5FGDYERQT3PBM
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: carrentalsystem


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080