cloud:
  aws:
    credentials:
      access-key: AKIAUJGTDGEPZXAO3AW7
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: carrentalmanagementsystem


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080